# Apache 2.0 from https://github.com/systeminit/si/tree/main/third-party/rust
omit_targets = []
extra_srcs = []
omit_srcs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
omit_deps = []
cargo_env = true

[[buildscript]]
[buildscript.gen_srcs]
