name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
      branches: [ '**' ]

jobs:
  run:
    name: CI
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Install Buck2
        uses: dtolnay/install-buck2@latest

      # - name: Install zstd
      #   run: sudo apt-get update && sudo apt-get install -y zstd wget

      - name: Unzip .zst file
        run: |
          zstd -d reindeer-x86_64-unknown-linux-gnu.zst -o ./reindeer
          chmod +x ./reindeer

      - name: Run build
        run: |
          ./test.sh
