name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
      branches: [ '**' ]

jobs:
  run:
    name: CI
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Run build
        run: |
          ./ci.sh
